name: Lint
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Format check
        run: npm run lint
